version: "3.7"

services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - /local-files:/files

  evolution-api:
    image: atendai/evolution-api:v1.7.4
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.evolution.rule=Host(`evolution.${DOMAIN_NAME}`)
      - traefik.http.routers.evolution.tls=true
      - traefik.http.routers.evolution.entrypoints=web,websecure
      - traefik.http.routers.evolution.tls.certresolver=mytlschallenge
      - traefik.http.services.evolution.loadbalancer.server.port=8080
    environment:
      - SERVER_URL=https://evolution.${DOMAIN_NAME}
      - AUTHENTICATION_API_KEY=&AMfUxcM5XxQ9amrC274
      - DATABASE_ENABLED=false
      - REDIS_ENABLED=false
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1029193574
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
    volumes:
      - evolution_data:/evolution/instances

  waha:
    image: devlikeapro/waha
    restart: always
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.waha.rule=Host(`waha.${DOMAIN_NAME}`)
      - traefik.http.routers.waha.tls=true
      - traefik.http.routers.waha.entrypoints=web,websecure
      - traefik.http.routers.waha.tls.certresolver=mytlschallenge
      - traefik.http.services.waha.loadbalancer.server.port=3000
    environment:
      - WHATSAPP_API_KEY=3JqCPredou7zFdg6y
    volumes:
      - waha_data:/app/.sessions

  symfony:
    image: ghcr.io/wendyaflearning/wedly-api:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.symfony.rule=Host(`api.wedly-apps.com`)
      - traefik.http.routers.symfony.tls=true
      - traefik.http.routers.symfony.entrypoints=web,websecure
      - traefik.http.routers.symfony.tls.certresolver=mytlschallenge
      - traefik.http.services.symfony.loadbalancer.server.port=80
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=/var/www/html/config/jwt/private.pem
      - JWT_PUBLIC_KEY=/var/www/html/config/jwt/public.pem
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
    volumes:
      - ./config/jwt:/var/www/html/config/jwt:ro

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  traefik_data:
    external: true
  n8n_data:
    external: true
  evolution_data:
  waha_data:
  db_data:
